name: docpocket
description: "DocVault feature package for managing and securing documents."
version: 0.0.1
homepage:

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  path_provider: ^2.1.2
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  share_plus: ^10.1.1
  intl: ^0.19.0
  uuid: ^4.3.3
  path: ^1.9.0
  open_filex: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9


flutter:
  uses-material-design: true
  assets:
    - docpocket_package/docpocket/pocket_assets/icon/